In [4]:
import pandas as pd
df = pd.read_csv("ca_housing_analytical_matrix.csv")
df_ca = pd.read_csv("realtor-data-ca.csv")

In [5]:
df.head()

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,...,sold_month,median_hh_income,urban_density_ratio,state_in_migration_rate,west_cpi_inflation,us_30yr_mortgage_rate,ca_unemployment_rate,log_price,log_house_size,is_cost_burdened
0,76008.0,for_sale,250000.0,7.0,3.0,0.19,1002149.0,Blythe,California,92225.0,...,9,69744.0,0.971108,0.025059,244.257,3.8900,5.9,12.429216,8.047510,0
1,22611.0,for_sale,287500.0,5.0,3.0,0.20,1230938.0,Blythe,California,92225.0,...,3,79601.0,0.972837,0.017306,260.994,4.4440,4.3,12.568978,7.403670,0
2,86230.0,for_sale,144549.0,3.0,1.0,0.29,994271.0,Blythe,California,92225.0,...,2,96000.0,0.972338,0.020847,301.158,3.7625,4.8,11.881374,6.995766,0
3,81166.0,for_sale,250000.0,3.0,2.0,0.15,1507474.0,Blythe,California,92225.0,...,9,80090.0,0.971229,0.020079,272.102,3.6050,4.0,12.429216,7.185387,0
4,81166.0,for_sale,299000.0,3.0,3.0,0.13,1612233.0,Blythe,California,92225.0,...,7,90002.0,0.971197,0.018288,275.597,3.0160,13.1,12.608199,7.629976,0

In [6]:
df.shape
df.columns

Index(['brokered_by', 'status', 'price', 'bed', 'bath', 'acre_lot', 'street',
       'city', 'state', 'zip_code', 'house_size', 'prev_sold_date',
       'sold_year', 'sold_month', 'median_hh_income', 'urban_density_ratio',
       'state_in_migration_rate', 'west_cpi_inflation',
       'us_30yr_mortgage_rate', 'ca_unemployment_rate', 'log_price',
       'log_house_size', 'is_cost_burdened'],
      dtype='str')

In [7]:
df.shape

(144299, 23)

In [8]:
df_ca.columns

Index(['brokered_by', 'status', 'price', 'bed', 'bath', 'acre_lot', 'street',
       'city', 'state', 'zip_code', 'house_size', 'prev_sold_date'],
      dtype='str')

In [23]:
df_pop = pd.read_csv("ca county population 2020-25.csv")
df_pop.columns

Index(['County', 'Revised  July 1, 2020', 'Revised  July 1, 2021',
       'Revised  July 1, 2022', 'Revised  July 1, 2023',
       'Revised  July 1, 2024', 'Preliminary  July 1, 2025'],
      dtype='str')

In [11]:
df_pop.head()

,County,"Revised July 1, 2020","Revised July 1, 2021","Revised July 1, 2022","Revised July 1, 2023","Revised July 1, 2024","Preliminary July 1, 2025"
0,Alameda,"1,683,829","1,661,283","1,651,884","1,653,486","1,659,982","1,661,903"
1,Alpine,"1,202","1,181","1,177","1,166","1,166","1,156"
2,Amador,"40,409","40,266","40,162","40,178","40,151","39,829"
3,Butte,"210,220","206,101","206,573","206,485","207,524","207,410"
4,Calaveras,"45,253","45,017","44,767","44,615","44,436","44,269"

In [15]:
df_hpi_county = pd.read_csv("hpi_at_county.csv")
df_hpi_county.columns

Index(['State', 'County', 'FIPS code', 'Year', 'Annual Change (%)', 'HPI',
       'HPI with 1990 base', 'HPI with 2000 base'],
      dtype='str')

In [18]:
df_ca_hpi = df_hpi_county[df_hpi_county["State"] == "CA"]
df_ca_hpi["County"].nunique()

58

In [22]:
df_ca_hpi["County"].unique()

<StringArray>
[        'Alameda',          'Alpine',          'Amador',           'Butte',
       'Calaveras',          'Colusa',    'Contra Costa',       'Del Norte',
       'El Dorado',          'Fresno',           'Glenn',        'Humboldt',
        'Imperial',            'Inyo',            'Kern',           'Kings',
            'Lake',          'Lassen',     'Los Angeles',          'Madera',
           'Marin',        'Mariposa',       'Mendocino',          'Merced',
           'Modoc',            'Mono',        'Monterey',            'Napa',
          'Nevada',          'Orange',          'Placer',          'Plumas',
       'Riverside',      'Sacramento',      'San Benito',  'San Bernardino',
       'San Diego',   'San Francisco',     'San Joaquin', 'San Luis Obispo',
       'San Mateo',   'Santa Barbara',     'Santa Clara',      'Santa Cruz',
          'Shasta',          'Sierra',        'Siskiyou',          'Solano',
          'Sonoma',      'Stanislaus',          'Sutter',          'Tehama',
         'Trinity',          'Tulare',        'Tuolumne',         'Ventura',
            'Yolo',            'Yuba']
Length: 58, dtype: str

In [25]:
df_hpi_zip5 = pd.read_csv("hpi_at_zip5.csv")
df_hpi_zip5.columns

Index(['Five-Digit ZIP Code', 'Year', 'Annual Change (%)', 'HPI',
       'HPI with 1990 base', 'HPI with 2000 base', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12'],
      dtype='str')

In [27]:
df_cainc = pd.read_csv("CAINC4_CA.csv")
df_cainc = df_cainc[["GeoName","Description","2020","2024"]]
df_cainc.head()

,GeoName,Description,2020,2024
0,California,Personal income (thousands of dollars),2.770489e+09,3.400237e+09
1,California,Nonfarm personal income 1/,2.751942e+09,3.379508e+09
2,California,Farm income 2/,1.854698e+07,2.072893e+07
3,California,Population (persons) 3/,3.952196e+07,3.943126e+07
4,California,Per capita personal income (dollars) 4/,7.010000e+04,8.623200e+04

In [29]:
df_cainc["GeoName"].unique()

<StringArray>
[         'California',         'Alameda, CA',          'Alpine, CA',
          'Amador, CA',           'Butte, CA',       'Calaveras, CA',
          'Colusa, CA',    'Contra Costa, CA',       'Del Norte, CA',
       'El Dorado, CA',          'Fresno, CA',           'Glenn, CA',
        'Humboldt, CA',        'Imperial, CA',            'Inyo, CA',
            'Kern, CA',           'Kings, CA',            'Lake, CA',
          'Lassen, CA',     'Los Angeles, CA',          'Madera, CA',
           'Marin, CA',        'Mariposa, CA',       'Mendocino, CA',
          'Merced, CA',           'Modoc, CA',            'Mono, CA',
        'Monterey, CA',            'Napa, CA',          'Nevada, CA',
          'Orange, CA',          'Placer, CA',          'Plumas, CA',
       'Riverside, CA',      'Sacramento, CA',      'San Benito, CA',
  'San Bernardino, CA',       'San Diego, CA',   'San Francisco, CA',
     'San Joaquin, CA', 'San Luis Obispo, CA',       'San Mateo, CA',
   'Santa Barbara, CA',     'Santa Clara, CA',      'Santa Cruz, CA',
          'Shasta, CA',          'Sierra, CA',        'Siskiyou, CA',
          'Solano, CA',          'Sonoma, CA',      'Stanislaus, CA',
          'Sutter, CA',          'Tehama, CA',         'Trinity, CA',
          'Tulare, CA',        'Tuolumne, CA',         'Ventura, CA',
            'Yolo, CA',            'Yuba, CA',                   nan]
Length: 60, dtype: str

In [28]:
df_cainc["Description"].unique()

<StringArray>
[                                   'Personal income (thousands of dollars) ',
                                                ' Nonfarm personal income 1/',
                                                            ' Farm income 2/',
                                                    'Population (persons) 3/',
                                    'Per capita personal income (dollars) 4/',
                                                 'Earnings by place of work ',
                     'Less: Contributions for government social insurance 5/',
 ' Employee and self-employed contributions for government social insurance ',
                   ' Employer contributions for government social insurance ',
                                          'Plus: Adjustment for residence 6/',
                                'Equals: Net earnings by place of residence ',
                                     'Plus: Dividends, interest, and rent 7/',
                                  'Plus: Personal current transfer receipts ',
                                                        'Wages and salaries ',
                                         'Supplements to wages and salaries ',
        ' Employer contributions for employee pension and insurance funds 8/',
                                                     'Proprietors' income 9/',
                                                 ' Farm proprietors' income ',
                                              ' Nonfarm proprietors' income ',
                                                                          nan]
Length: 20, dtype: str